# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3SW6sQlyClkVNYVwf_zRJls9KMday6A
"""

# Exercise 2
# Generate a vector of random numbers with a seed equal to your student number. Your vector should have 10,000 correct digits between zero and twenty (including twenty). Then calculate and print the number of repetitions of each number between zero and twenty in the production list.

import torch

# Set the seed for reproducibility
torch.manual_seed(400121027)

# Generate a vector of 10,000 random integers between 0 and 20 (inclusive)
vector = torch.randint(0, 21, (10000,))

# Initialize a dictionary to count occurrences of each integer
counts = {i: 0 for i in range(21)}

# Count the occurrences of each integer in the vector
for num in vector:
    counts[int(num)] += 1

# Print the counts
for num, count in counts.items():
    print(f"Number {num}: {count} times")