# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KUfcpuGtkdEURrbw1ub26UrFT0pdY3_I
"""

# Exercise 1
# Draw a map of sin and cos between zero and 2p and draw the area between the two curves as hatched.



import torch
import matplotlib.pyplot as plt
import numpy as np

# Create an array of x values from 0 to 2π
x = torch.linspace(0, 2 * torch.pi, 1000)

# Compute the values of sin(x) and cos(x)
y_sin = torch.sin(x)
y_cos = torch.cos(x)

# Convert values to numpy for plotting
x_np = x.numpy()
y_sin_np = y_sin.numpy()
y_cos_np = y_cos.numpy()

# Plot the curves
plt.plot(x_np, y_sin_np, label='sin(x)')
plt.plot(x_np, y_cos_np, label='cos(x)')

# Shade the area between the curves
plt.fill_between(x_np, y_sin_np, y_cos_np, where=(y_sin_np > y_cos_np), interpolate=True, color='red', alpha=0.3, hatch='/')
plt.fill_between(x_np, y_sin_np, y_cos_np, where=(y_sin_np <= y_cos_np), interpolate=True, color='blue', alpha=0.3, hatch='\\')

# Add title and labels
plt.title('Area between sin(x) and cos(x)')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()

# Display the plot
plt.show()